# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0003_auto_20171117_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_creating',
            field=models.DateField(auto_now_add=True, help_text='Дата регистрации'),
        ),
    ]
