# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0007_auto_20171117_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninfo',
            name='prefering_connection',
            field=models.DateField(default='django.utils.timezone.now', help_text='Предпочитаемая дата подключения'),
        ),
    ]
