# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0009_auto_20171117_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninfo',
            name='prefering_connection',
            field=models.DateField(help_text='Предпочитаемая дата подключения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_creating',
            field=models.DateField(default=datetime.date(2017, 11, 17), help_text='Дата регистрации'),
        ),
    ]
