# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0012_auto_20171117_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_creating',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата регистрации'),
        ),
    ]
