# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blank', '0014_auto_20171117_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creating', models.DateField(default=django.utils.timezone.now, help_text='Дата регистрации')),
                ('name', models.CharField(help_text='Введите имя абонента', max_length=15)),
                ('surname', models.CharField(help_text='Введите фамилию абонента', max_length=15)),
                ('patronymic', models.CharField(help_text='Введите отчество абонента', max_length=20)),
                ('passport_data', models.CharField(help_text='Паспортные данные', max_length=100)),
                ('home', models.CharField(help_text='Введите номер дома', max_length=3)),
                ('flat', models.CharField(help_text='Введите номер квартиры', max_length=4)),
                ('contact_number', models.CharField(help_text='Контактный номер абонента', max_length=30)),
                ('prefering_connection', models.DateField(blank=True, help_text='Предпочитаемая дата подключения', null=True)),
                ('tarrif', models.CharField(blank=True, choices=[('s40', 'Скоростной 40'), ('s60', 'Скоростной 60'), ('s80', 'Скоростной 80'), ('s100', 'Скоростной 100'), ('s120', 'Скоростной 120'), ('s140', 'Скоростной 140'), ('s160', 'Скоростной 160'), ('s200', 'Скоростной 200'), ('s240', 'Скоростной 240')], default='s40', help_text='Предпочитаемый тарифный план', max_length=4, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
