# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0018_auto_20171120_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+9989', help_text='Контактный номер абонента', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flat',
            field=models.CharField(help_text='Введите номер квартиры', max_length=4),
        ),
    ]
