# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0019_auto_20171120_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_number',
        ),
    ]
