# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0023_profile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, default='+9989', help_text='Контактный номер абонента', max_length=30, null=True),
        ),
    ]
