# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0030_auto_20171124_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
