# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0035_auto_20171125_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Контактный номер абонента', max_length=30, null=True),
        ),
    ]
