# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0053_auto_20171205_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefering_connection',
            field=models.CharField(help_text='Предпочитаемая дата подключения', max_length=15),
        ),
    ]
