# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0055_auto_20171206_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(help_text='Контактный номер абонента', max_length=30),
        ),
    ]
