# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0057_auto_20171206_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='flat',
            field=models.CharField(help_text='Введите номер квартиры', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home',
            field=models.CharField(help_text='Введите номер дома', max_length=5),
        ),
    ]
