# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0062_auto_20171211_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Открыта', 'Открыта'), ('Закрыта', 'Закрыта')], max_length=15, null=True),
        ),
    ]
