# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarrif', models.CharField(choices=[('s40', 'Скоростной 40'), ('s60', 'Скоростной 60'), ('s80', 'Скоростной 80'), ('s100', 'Скоростной 100'), ('s120', 'Скоростной 120'), ('s140', 'Скоростной 140'), ('s160', 'Скоростной 160'), ('s200', 'Скоростной 200'), ('s240', 'Скоростной 240')], help_text='Предпочитаемый тарифный план', max_length=4)),
                ('prefering_connection', models.DateField(help_text='Предпочитаемая дата подключения')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя абонента', max_length=15)),
                ('surname', models.CharField(help_text='Введите фамилию абонента', max_length=15)),
                ('patronymic', models.CharField(help_text='Введите отчество абонента', max_length=20)),
                ('contact_number', models.CharField(help_text='Контактный номер абонента', max_length=30)),
                ('date_creating', models.DateField(auto_now=True)),
                ('home', models.CharField(help_text='Введите номер дома', max_length=3)),
                ('flat', models.CharField(help_text='Введите номер квартиры', max_length=4)),
                ('passport_data', models.CharField(help_text='Паспортные данные', max_length=100)),
            ],
        ),
    ]
