# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0005_auto_20171117_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninfo',
            name='prefering_connection',
            field=models.DateField(help_text='Предпочитаемая дата подключения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_creating',
            field=models.DateField(help_text='Дата регистрации'),
        ),
    ]
