# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0010_auto_20171117_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectioninfo',
            old_name='tarrif',
            new_name='Smart_tarrif',
        ),
        migrations.AddField(
            model_name='connectioninfo',
            name='Samrt',
            field=models.CharField(default='SAMIY SMARTOVIY POLE', max_length=100),
        ),
    ]
