# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:16
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0016_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Контактный номер абонента', max_length=30, null=True),
        ),
    ]
