# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 12:27
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0022_remove_profile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+9989', help_text='Контактный номер абонента', max_length=30, null=True),
        ),
    ]
