# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0024_auto_20171121_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(blank=True, max_length=100, null=True)),
                ('two', models.CharField(blank=True, max_length=100, null=True)),
                ('three', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
