# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0025_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefering_connection',
            field=models.CharField(blank=True, help_text='Предпочитаемая дата подключения', max_length=15, null=True),
        ),
    ]
