# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0026_auto_20171123_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_creating',
            field=models.DateField(blank=True, help_text='Дата регистрации', null=True),
        ),
    ]
