# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0027_auto_20171124_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarrif',
            field=models.CharField(blank=True, default='Скоростной 40', help_text='Предпочитаемый тарифный план', max_length=20, null=True),
        ),
    ]
