# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0034_remove_profile_passport_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarrif',
            field=models.CharField(blank=True, choices=[('s40', 'Скоростной 40'), ('s60', 'Скоростной 60'), ('s80', 'Скоростной 80'), ('s100', 'Скоростной 100'), ('s120', 'Скоростной 120'), ('s140', 'Скоростной 140'), ('s160', 'Скоростной 160'), ('s200', 'Скоростной 200'), ('s240', 'Скоростной 240')], max_length=15, null=True),
        ),
    ]
