# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0038_auto_20171128_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manager',
        ),
    ]
