# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0040_profile_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='Улица/Массив', max_length=20, null=True),
        ),
    ]
