# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0041_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('o', 'Открыта'), ('n', 'Новая'), ('c', 'Закрыта')], default='o', max_length=1),
        ),
    ]
