# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0042_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_creating',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Дата регистрации', null=True),
        ),
    ]
