# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0050_auto_20171201_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_see_all_blank', 'View all blanks'),)},
        ),
    ]
