# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blank', '0056_auto_20171206_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(help_text='Улица/Массив', max_length=20),
        ),
    ]
