# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='router',
            old_name='sn',
            new_name='SN',
        ),
    ]
